name: custed2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.2.0
  get_it: ^4.0.0-release-candidate

  html: ^0.14.0+3
  path: ^1.6.4
  convert: ^2.1.1
  json_annotation: ^3.0.0
  crypto: ^2.1.3
  photo_view: ^0.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_advanced_networkimage:
    git:
      url: https://github.com/CustedNG/flutter_advanced_networkimage.git
      ref: master

  flutter_cupertino_settings:
    git:
      url: https://github.com/CustedNG/flutter_cupertino_settings.git
      ref: master

  expandable_bottom_sheet: ^0.2.1+1

  alice:
    git:
      url: https://github.com/xtyxtyx/alice.git
      ref: master

  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0

  path_provider: ^1.5.1
  android_path_provider: ^0.1.1

  hive: ^1.3.0
  hive_flutter: ^0.3.0+1

  webview_flutter: ^0.3.19+5
  flutter_inappwebview: ^4.0.0

  otp: ^1.0.3
  install_plugin: ^2.0.1
  save_in_gallery: ^0.1.3
  url_launcher: ^5.5.0
  get_ip: ^0.4.0
  add_2_calendar: ^1.3.1
  share_extend: ^1.1.1
  connectivity: '>=0.4.9+2 <2.0.0'

  http: ^0.12.0+4
  cookie_jar: ^1.0.1
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0

  countly_flutter: 20.04.0

  flutter_svg: 0.18.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner: ^1.7.1
  hive_generator: ^0.7.0
  retrofit_generator: ^1.0.2+2
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/map/simple/
    - assets/avatar/
    - assets/icon/
    - assets/updating.gif
    - assets/calendar/2019-2.png
    - assets/script/
    - assets/bg/
    - assets/wechat/
